/* action.c */
int act_remove_gems(int arg);
int act_sit_throne(int arg);
int act_kick_stairs(void);
int act_up_stairs(void);
int act_down_stairs(void);
int act_drink_fountain(void);
int act_wash_fountain(void);
int act_down_shaft(void);
int act_up_shaft(void);
static volshaft_climbed(int object);
int act_desecrate_altar(void);
int act_donation_pray(void);
int act_just_pray(void);
static act_prayer_heard(void);
int act_ignore_altar(void);
int act_open_chest(int x, int y);
int act_open_door(int x, int y);
/* bill.c */
static letter1(void);
static letter2(void);
static letter3(void);
static letter4(void);
static letter5(void);
static letter6(void);
int mailbill(void);
/* config.c */
/* create.c */
int makeplayer(void);
int newcavelevel(register int x);
static makemaze(int k);
int eat(register int xx, register int yy);
static cannedlevel(int k);
static treasureroom(register int lv);
static troom(int lv, int xsize, int ysize, int tx, int ty, int glyph);
static makeobject(register int j);
static fillmroom(int n, int what, int arg);
static froom(int n, int itm, int arg);
static fillroom(int what, int arg);
int fillmonst(int what);
static sethp(int flg);
static checkgen(void);
/* data.c */
/* diag.c */
int savegame(char *fname);
int restoregame(char *fname);
static greedy(void);
static fsorry(void);
static fcheat(void);
/* display.c */
int bottomline(void);
int bottomhp(void);
int bottomspell(void);
int bottomdo(void);
int bot_linex(void);
int bottomgold(void);
static bot_hpx(void);
static bot_spellx(void);
static botside(void);
int draws(int xmin, int xmax, int ymin, int ymax);
int drawscreen(void);
int showcell(int x, int y);
int show1cell(int x, int y);
int showplayer(void);
int moveplayer(int dir);
int seemagic(int arg);
static seepage(void);
/* fgetlr.c */
char *fgetlr(char *bp, int bpsize, FILE *fp);
/* fortune.c */
char *fortune(char *file);
/* global.c */
int raiselevel(void);
int loselevel(void);
int raiseexperience(register long x);
int loseexperience(register long x);
int losehp(register int x);
int losemhp(register int x);
int raisehp(register int x);
int raisemhp(register int x);
int raisemspells(register int x);
int losemspells(register int x);
int makemonst(register int lev);
int positionplayer(void);
int recalc(void);
int quit(void);
int more(void);
int take(int itm, int arg);
int drop_object(int k);
int enchantarmor(void);
int enchweapon(void);
int pocketfull(void);
int nearbymonst(void);
int stealsomething(void);
int emptyhanded(void);
int creategem(void);
int adjustcvalues(int itm, int arg);
int getpassword(void);
int getyn(void);
int packweight(void);
int rnd(int x);
int rund(int x);
int gettokstr(register char *str);
/* help.c */
int help(void);
int welcome(void);
int retcont(void);
static openhelp(void);
/* io.c */
int setupvt100(void);
int clearvt100(void);
int ttgetch(void);
int scbr(void);
int sncbr(void);
int newgame(void);
int lprintf();
int lprint(register long x);
int lwrite(register char *buf, int len);
long lgetc(void);
int lrfill(register char *adr, int num);
char *lgetw(void);
char *lgetl(void);
int lcreat(char *str);
int lopen(char *str);
int lappend(char *str);
int lrclose(void);
int lwclose(void);
int lprcat(register char *str);
int cursor(int x, int y);
int cursors(void);
int init_term(void);
int cl_line(int x, int y);
int cl_up(register int x, register int y);
int cl_dn(register int x, register int y);
int standout(register char *str);
int set_score_output(void);
int lflush(void);
static int ttputch(int c);
static flush_buf(void);
char *tmcapcnv(register char *sd, register char *ss);
int beep(void);
/* main.c */
int main(int argc, char **argv);
int showstr(void);
int qshowstr(void);
int t_setup(register int count);
int t_endup(register int count);
int showwear(void);
int showwield(void);
int showread(void);
int showeat(void);
int showquaff(void);
int show1(register int idx, register char *str2[]);
int show3(register int index);
int randmonst(void);
int parse(void);
int parse2(void);
int run(int dir);
int wield(void);
int ydhi(int x);
int ycwi(int x);
int wear(void);
int dropobj(void);
int readscr(void);
int eatcookie(void);
int quaff(void);
static whatitem(char *str);
unsigned long readnum(long mx);
/* monster.c */
int createmonster(int mon);
static int cgood(register int x, register int y, int itm, int monst);
int createitem(int it, int arg);
int vxy(int *x, int *y);
int hitmonster(int x, int y);
int hitm(int x, int y, register amt);
int hitplayer(int x, int y);
static dropsomething(int monst);
int dropgold(register int amount);
int something(int level);
int newobject(register int lev, register int *i);
static spattack(int x, int xx, int yy);
int checkloss(int x);
/* moreobj.c */
int oaltar(void);
int othrone(int arg);
int odeadthrone(void);
int ochest(void);
int ofountain(void);
int fntchange(int how);
static fch(int how, long *x);
int drink_fountain(void);
int wash_fountain(void);
int enter(void);
int remove_gems(void);
int sit_on_throne(void);
int kick_stairs(void);
int up_stairs(void);
int down_stairs(void);
int open_something(void);
int close_something(void);
int desecrate_altar(void);
int pray_at_altar(void);
/* movem.c */
void movemonst(void);
void build_proximity_ripple(void);
void move_scared(int i, int j);
void move_smart(int i, int j);
void move_dumb(int i, int j);
void mmove(int aa, int bb, int cc, int dd);
/* msdos.c */
/* nap.c */
int nap(register int x);
static napms(int time);
/* object.c */
int lookforobject(int do_ident, int do_pickup, int do_action);
int ostairs(int dir);
int oteleport(int err);
int opotion(int pot);
int quaffpotion(int pot, int set_known);
int oscroll(int typ);
int adjtime(register long tim);
int read_scroll(int typ);
int oorb(void);
int opit(void);
int obottomless(void);
int oelevator(int dir);
int ostatue(void);
int omirror(void);
int obook(void);
int readbook(register int lev);
int ocookie(void);
int ogold(int arg);
int ohome(void);
int iopts(void);
int ignore(void);
int prompt_enter(void);
int prompt_volshaft(int dir);
int o_open_door(void);
int o_closed_door(void);
/* regen.c */
int regen(void);
/* savelev.c */
int savelevel(void);
int getlevel(void);
/* scores.c */
int readboard(void);
int writeboard(void);
int makeboard(void);
int hashewon(void);
long paytaxes(long x);
int winshou(void);
int shou(int x);
int showscores(void);
int showallscores(void);
int sortboard(void);
int newscore(long score, char *whoo, int whyded, int winner);
int new1sub(long score, int i, char *whoo, long taxes);
int new2sub(long score, int i, char *whoo, int whyded);
int died(int x);
int diedsub(int x);
int diedlog(void);
int getplid(char *nam);
/* signal.c */
static s2choose(void);
void cntlc(void);
static sgam(void);
static tstop(void);
void sigfpe(void);
static sigbus(void);
static sigill(void);
static sigtrap(void);
static sigiot(void);
static sigemt(void);
static sigsegv(void);
static sigsys(void);
static sigpipe(void);
static sigterm(void);
int sigsetup(void);
static sigpanic(int sig);
/* spells.c */
int cast(void);
static speldamage(int x);
static void create_guardian(int monst, int x, int y);
static loseint(void);
static isconfuse(void);
static nospell(int x, int monst);
int fullhit(int xx);
static direct(int spnum, int dam, char *str, int arg);
int godirect(int spnum, int dam, char *str, int delay, int cshow);
int ifblind(int x, int y);
static tdirect(int spnum);
static omnidirect(int spnum, int dam, char *str);
int dirsub(int *x, int *y);
static dirpoly(int spnum);
int annihilate(void);
static genmonst(void);
/* spheres.c */
int newsphere(int x, int y, int dir, int life);
int rmsphere(int x, int y);
static sphboom(int x, int y);
int movsphere(void);
/* store.c */
int dnd_2hed(void);
int dnd_hed(void);
int dndstore(void);
static handsfull(void);
static outofstock(void);
static nogold(void);
static dnditem(register int i);
int sch_hed(void);
int oschool(void);
int obank(void);
int obank2(void);
static banktitle(char *str);
int ointerest(void);
int obanksub(void);
static otradhead(void);
int otradiven(void);
int cleartradiven(int i);
int otradepost(void);
int cnsitm(void);
int olrs(void);
/* tgetent.c */
int tgetent(char *bp, char *name);
static FILE *find_file(char *bp);
int gotcha(char *bp, char *name);
/* tgetstr.c */
char *tgetstr(char *id, char **area);
static char *decode(char *bp, char **area);
char *do_esc(char *out, char *in);
/* tgoto.c */
char *tgoto(char *cm, int destcol, int destline);
static process(void);
/* tok.c */
int yylex(void);
int flushall(void);
int sethard(int hard);
int readopts(void);
/* tputs.c */
int tputs(char *cp, int affcnt, int (*outc)(void));
static do_padding(int ptime, int (*outc)(void));
/* vms.c */
int vread(int fd, char *buf, int size);
